### ISSUE TITLE
показывать пользователю где он ключевой акционер

### ISSUE THREAD

**Issue by IgorShishkin12** [FismanMaxim/MiptProject#22]

**Comment by DmitryDos** [comment]
Теперь, в случае регистрации пользователя таблица будет расширятся до 5 столбцов: 
Компания, ваши акции, являетесь ли ключевым акционерном, цена акции, доступно акций для покупки.

Обновлена таблица: "Персональные данные". Теперь она содержит:
 Имя компании, ваших акций, являетесь ли ключевым акционером
