### ISSUE TITLE
Классы базы данных InMemoryCompany и InMemoryUser должны реализовывать интерфейс EntityRepository

### ISSUE THREAD

**Issue by FismanMaxim** [FismanMaxim/MiptProject#8]
Классы базы данных InMemoryCompany и InMemoryUser должны реализовывать интерфейс EntityRepository (EntityRepository<Company> и EntityRepository<User> соответственно), как это делают используемые временно сейчас классы InMemoryCompanyRepository и InMemoryUserRepository.

Помимо этого, для того чтобы можно было создать экземпляр классов InMemoruCompany и InMemoryUser, они не должны быть вложенными в Database, т.к. это вызывает синтаксическую ошибку.

**Comment by IgorShishkin12** [comment]
проблема решена
